services:
  - type: web
    name: hybrid-movie-recommender
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    runtime: python3
    region: oregon
    plan: free
